import Image from "next/image";
import { Icon } from "@/components/icon";
import { MobileNavigation } from "@/components/mobile-navigation";
import { ThemeToggle } from "@/components/theme-toggle";
import { caseStudies, expertise, getExperienceYears, navigation, site, writing } from "@/data/portfolio";

function ExternalLink({ href, children, className = "" }: { href: string; children: React.ReactNode; className?: string }) {
  return <a href={href} target="_blank" rel="noopener noreferrer" className={className}>{children}</a>;
}

export default function Home() {
  const experienceYears = getExperienceYears();

  return (
    <><header className="site-header"><div className="container nav-wrap"><a className="brand" href="#top" aria-label="Pulasthi Aberathne home"><Image src="/pa-logo-light.png" alt="PA" width={39} height={47} className="theme-logo logo-light" priority /><Image src="/pa-logo-dark.png" alt="" width={39} height={47} className="theme-logo logo-dark" priority /><span className="brand-name">Pulasthi</span></a><nav aria-label="Primary navigation" className="nav-links desktop-nav">{navigation.map((item) => <a key={item.href} href={item.href}>{item.label}</a>)}</nav><div className="nav-actions"><MobileNavigation /><ThemeToggle /><a href="#contact" className="nav-contact">Let&apos;s talk <Icon name="arrow-up-right" className="size-3.5" /></a></div></div></header><main>
      <section id="top" className="hero-section" aria-labelledby="hero-title"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> Available for select engineering projects</p><h1 id="hero-title">Pulasthi<br /><span>Aberathne</span></h1><p className="hero-role">Full-Stack Engineer</p><p className="hero-lede">I build reliable production systems across backend, frontend, and cloud infrastructure.</p><p className="hero-support">Senior software engineer with {experienceYears}+ years of experience building and operating production software across distributed systems, APIs, web and mobile applications, and cloud infrastructure.</p><div className="hero-actions"><a href="#work" className="button button-primary">View my work <Icon name="arrow-up-right" className="size-4" /></a><a href="/contact" className="button button-secondary">Get in touch</a></div><nav className="social-links" aria-label="Social links"><ExternalLink href={site.github} className="social-link"><Icon name="github" className="size-4" /> GitHub</ExternalLink><ExternalLink href={site.linkedin} className="social-link"><Icon name="linkedin" className="size-4" /> LinkedIn</ExternalLink></nav></div><div className="architecture-panel" aria-hidden="true"><div className="architecture-label">A systems view</div><div className="architecture-canvas"><svg className="architecture-lines" viewBox="0 0 100 100" preserveAspectRatio="none"><line className="connector connector-client" x1="18" y1="39" x2="47" y2="48" vectorEffect="non-scaling-stroke" /><line className="connector connector-services" x1="47" y1="48" x2="84" y2="29" vectorEffect="non-scaling-stroke" /><line className="connector connector-data" x1="47" y1="48" x2="82" y2="68" vectorEffect="non-scaling-stroke" /><line className="connector connector-cloud" x1="47" y1="48" x2="37" y2="78" vectorEffect="non-scaling-stroke" /></svg><div className="arch-node node-client"><span className="node-dot" /><span>Client</span></div><div className="arch-node node-api"><span className="node-dot" /><span>API</span></div><div className="arch-node node-services"><span className="node-dot" /><span>Services</span></div><div className="arch-node node-data"><span className="node-dot" /><span>Data</span></div><div className="arch-node node-cloud"><span className="node-dot" /><span>Cloud</span></div><div className="architecture-caption"><span>01</span> reliability is a design constraint</div></div></div></div><div className="container scroll-cue"><span>Scroll to explore</span><span className="scroll-line" /></div></section>

      <section id="about" className="section about-section" aria-labelledby="about-title"><div className="container section-grid"><div className="section-intro"><p className="section-kicker">/ 01 — About</p><h2 id="about-title">Engineering with the whole system in view.</h2></div><div className="about-copy"><p className="lead-copy">I&apos;m a full-stack software engineer with {experienceYears}+ years of experience building and maintaining production software. My work spans backend services and APIs, distributed systems, frontend and mobile applications, cloud infrastructure, and the troubleshooting that happens after launch.</p><p>I currently work on enterprise distributed systems using Java, Spring Boot, NestJS, TypeScript, React, gRPC / Protocol Buffers, Kubernetes, and GCP. Previously, I worked extensively with Node.js, React Native, PostgreSQL, MongoDB, and AWS.</p><p>That range helps me contribute across boundaries: from authentication and integrations to code review, technical leadership, and the details that make a system dependable in practice.</p></div></div></section>

      <section id="expertise" className="section expertise-section" aria-labelledby="expertise-title"><div className="container"><div className="section-heading"><div><p className="section-kicker">/ 02 — Expertise</p><h2 id="expertise-title">Capability areas</h2></div><p className="heading-note">A practical toolkit shaped by production work, not a checklist.</p></div><div className="expertise-grid">{expertise.map((item) => <article className="expertise-card" key={item.number}><div className="card-topline"><span>{item.number}</span><span className="card-arrow"><Icon name="arrow-up-right" className="size-4" /></span></div><h3>{item.title}</h3><p>{item.description}</p><div className="tag-list">{item.technologies.map((technology) => <span key={technology} className="tag">{technology}</span>)}</div></article>)}</div></div></section>

      <section id="work" className="section work-section" aria-labelledby="work-title"><div className="container"><div className="section-heading"><div><p className="section-kicker">/ 03 — Selected work</p><h2 id="work-title">Systems I&apos;ve worked on</h2></div><p className="heading-note">A few representative case studies. The details stay grounded in what can be shared.</p></div><div className="case-study-list">{caseStudies.map((study) => <article className="case-study" key={study.number}><div className="case-number">{study.number}</div><div className="case-main"><p className="case-type">{study.type}</p><h3>{study.title}</h3><p className="case-description">{study.description}</p>{study.details.length > 0 && <ul className="case-details">{study.details.map((detail) => <li key={detail}>{detail}</li>)}</ul>}{study.number === "01" && <a className="case-study-link" href="/work/location-discovery-platform">Read case study <Icon name="arrow-up-right" className="size-4" /></a>}{study.number === "02" && <a className="case-study-link" href="/work/zebra-nucleus">Read case study <Icon name="arrow-up-right" className="size-4" /></a>}<div className="tag-list">{study.technologies.map((technology) => <span key={technology} className="tag">{technology}</span>)}</div></div><div className="case-mark" aria-hidden="true"><span /></div></article>)}</div></div></section>

      <section id="writing" className="section writing-section" aria-labelledby="writing-title"><div className="container writing-layout"><div><p className="section-kicker">/ 04 — Blog</p><h2 id="writing-title">Notes from the field.</h2></div><div className="writing-card"><p className="writing-label">Featured article</p><h3>{writing.title}</h3><p>{writing.description}</p><ExternalLink href={writing.href} className="text-link">Read on Medium <Icon name="arrow-up-right" className="size-4" /></ExternalLink></div><a href="/blog" className="view-all">Visit the blog <Icon name="arrow-up-right" className="size-4" /></a></div></section>

      <section id="contact" className="contact-section" aria-labelledby="contact-title"><div className="container contact-inner"><p className="section-kicker">/ 05 — Contact</p><h2 id="contact-title">Let&apos;s build something reliable.</h2><p>I&apos;m open to discussing engineering projects, technical collaboration, and opportunities where I can help build or improve production software.</p><div className="contact-links"><a className="contact-email" href={`mailto:${site.email}`}><Icon name="mail" className="size-5" />{site.email}</a><ExternalLink href={site.linkedin} className="contact-link">LinkedIn <Icon name="arrow-up-right" className="size-4" /></ExternalLink><ExternalLink href={site.github} className="contact-link">GitHub <Icon name="arrow-up-right" className="size-4" /></ExternalLink></div></div></section>

      </main><footer className="site-footer"><div className="container footer-inner"><div><p className="footer-name">Pulasthi Aberathne</p><p className="footer-role">Full-Stack Engineer</p></div><div className="footer-right"><div className="footer-links"><ExternalLink href={site.github}>GitHub</ExternalLink><ExternalLink href={site.linkedin}>LinkedIn</ExternalLink><ExternalLink href={site.medium}>Medium</ExternalLink></div><p className="copyright">© {new Date().getFullYear()} Pulasthi Aberathne</p></div></div></footer></>
  );
}
